### ISSUE TITLE
Dockerfile update: Branch MacroFlask

### ISSUE THREAD

**Issue by ajlacey** [Project-Reclass/toynet-flask#24]
flask init-db does not work in the container build, because it is dependent on a docker client being available. When running the container the docker socket should be mounted: -v /var/run/docker.sock:/var/run/docker.sock
this will also require the CMD to be updated to CMD ["flask", "init-db", "&&", "flask", "run"] or utilize an entrypoint to accomplish the same.
PR: https://github.com/Project-Reclass/toynet-flask/pull/23

**Comment by blazebissar** [comment]
Resolved with PR #23
