### ISSUE TITLE
Device names allow for spaces after device name

### ISSUE THREAD

**Issue by scottjr632** [Project-Reclass/toynet-flask#40]
Currently, you can make a device with a name `H1      ` or any other name with a space or multiple spaces at the end of the device name. This makes it so that it is very hard to tell that there are spaces and makes it impossible to run a command like `ping H1` due to how spaces are parsed for commands.

A simple way to solve this could be to replace the spaces in [this line](https://github.com/Project-Reclass/toynet-flask/blob/main/flasksrc/session.py#L464) with nothing. Or we could also validate the name has no space and if it does have spaces we could return an error for a bad request. 

Currently the frontend disallows spaces in the inputs for device names, however, this is not full proof and there could be a time in the future where someone else creates an input for a device name and leaves out the space sanitization. This could cause unwanted bugs in the future that can be hard to track down and be annoying to users.

**Comment by ajlacey** [comment]
I'm thinking that device names _should_ be able to have spaces, but not trailing spaces. I will look at ensuring excess spaces are sanitized on host creation in session.py

**Comment by ajlacey** [comment]
I'll bring this up at project hour too, but I'm thinking this applies to all device names, not just hosts. Is that your understanding, @scottjr632?

**Comment by ajlacey** [comment]
relevant RFCs: 
https://datatracker.ietf.org/doc/html/rfc952
https://datatracker.ietf.org/doc/html/rfc1123

- 2.1  Host Names and Numbers

      The syntax of a legal Internet host name was specified in RFC-952
      [DNS:4].  One aspect of host name syntax is hereby changed: the
      restriction on the first character is relaxed to allow either a
      letter or a digit.  Host software MUST support this more liberal
      syntax.

      Host software MUST handle host names of up to 63 characters and SHOULD handle host names of up to 255 characters.

      Whenever a user inputs the identity of an Internet host, it SHOULD  be possible to enter either (1) a host domain name or (2) an IP address in dotted-decimal ("#.#.#.#") form.  The host SHOULD check the string syntactically for a dotted-decimal number before looking it up in the Domain Name System.
